config/routes.rb
require 'subdomain_router'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints(subdomain: '') do
    get '' => redirect { |_, request| "http://www.#{request.host_with_port}" }
    get '*glob' => redirect { |_, request| "http://www.#{request.host_with_port}#{request.fullpath}" }
  end

  constraints(subdomain: SubdomainRouter::Config.default_subdomain) do
    resources :users, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    resources :photographs, only: :index

    root(to: 'users#new')

    # require 'sidekiq/web'
    # require 'admin_constraint'
    # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  end

  constraints(SubdomainRouter::Constraint) do
    resource :account, only: [:show, :edit, :update, :destroy]
    resources :airports, only: [:index, :show] do
      resources :flights, only: :index
    end
    resources :flights, only: [:index, :show, :edit, :update] do
      resources :photographs, only: [:index, :create]
    end
    resources :imports, only: [:new, :create, :show]
    resources :people, only: [:index, :show] do
      resources :flights, only: :index
    end

    get '' => 'accounts#show'
  end
end

app/models/flight.rb
# An instance of one or more {Person people} taking an {Aircraft} on a flight
# from one {Airport} to another. A flight is exclusive to a {User} account.
#
# Flights have a `sequence` column that sequences flights in order by date.
# Two flights occurring on the same day have an arbitrary but consistent
# ordering. Flights are unsequenced when first created; you must call the
# {User#update_flight_sequence!} method to sequence a user's flights.
#
# Fields
# ------
#
# |              |                                                                                                           |
# |:-------------|:----------------------------------------------------------------------------------------------------------|
# | `duration`   | The length of the flight, in hours.                                                                       |
# | `logbook_id` | The unique ID assigned to this person by the user's logbook; used for matching flights in future imports. |
# | `has_blog`   | `true` if a blog entry has been written for this flight.                                                  |
# | `has_photos` | `true` if the flight has at least one {Photograph}.                                                       |
# | `sequence`   | A number ordering the flights: 1 is the first of a user's flights, and so on from there.                  |
#
# Metadata
# --------
#
# |           |                                                            |
# |:----------|:-----------------------------------------------------------|
# | `remarks` | The pilot's notes about what transpired during the flight. |
# | `blog`    | Markdown-formatted blog entry about the flight.            |
#
# Associations
# ------------
#
# |             |                                                                        |
# |:------------|:-----------------------------------------------------------------------|
# | `user`      | The {User} account owning the flight.                                  |
# | `aircraft`  | The {Aircraft} the flight was taken in.                                |
# | `occupants` | All {Occupant Occupants} present on the flight (PIC and SIC included). |

class Flight < ApplicationRecord
  include HasMetadataColumn
  include Slugalicious

  belongs_to :user, inverse_of: :flights
  belongs_to :aircraft, inverse_of: :flights
  has_many :photographs, inverse_of: :flight, dependent: :delete_all
  has_many :stops, inverse_of: :flight, dependent: :delete_all
  has_many :occupants, inverse_of: :flight, dependent: :delete_all

  slugged ->(flight) { "#{flight.date.strftime '%Y-%m-%d'} #{flight.destinations.map(&:airport).map(&:identifier).join('-')}" },
          scope:     ->(flight) { flight.user.subdomain },
          slugifier: ->(str) { str.remove_formatting.replace_whitespace('_').collapse('_') }

  has_metadata_column(
      remarks: { length: { maximum: 1_000_000 }, allow_blank: true },
      blog:    { allow_blank: true }
  )

  validates :duration,
            presence:     true,
            numericality: { greater_than: 0.0 }
  validates :logbook_id,
            presence:   true,
            uniqueness: { scope: :user_id }
  validates :date,
            presence: true
  validates :origin_id,
            presence: true
  validates :destination_id,
            presence: true
  validates :sequence,
            numericality: { only_integer: true, greater_than_or_equal_to: 1 },
            uniqueness:   { scope: :user_id },
            allow_blank:  true

  before_save { |obj| obj.has_blog = obj.blog.present?; true }

  accepts_nested_attributes_for :photographs, allow_destroy: true, reject_if: ->(attrs) { attrs['image'].nil? and attrs['id'].nil? }

  # @private
  def origin() user.destinations.where(airport_id: origin_id).first end
  # @private
  def destination() user.destinations.where(airport_id: destination_id).first end
  # @private
  def origin=(dest) self.origin_id = dest.try(:airport_id) end
  # @private
  def destination=(dest) self.destination_id = dest.try(:airport_id) end

  # @return [Array<Destination>] The origin, destination, and all intermediate
  #   stops, ordered in sequence.

  def destinations
    ids   = [origin_id, stops.order('sequence ASC').map(&:destination_id), destination_id].flatten.compact
    scope = user.destinations.where(airport_id: ids)
    scope = yield(scope) if block_given?
    dests = scope.to_a
    ids.map { |id| dests.detect { |dest| dest.airport_id == id } }
  end

  # @return [Flight, nil] The user's previous flight, or `nil` if this is the
  #   first flight or an as-yet unsequenced flight.

  def previous
    return nil unless sequence
    @previous ||= user.flights.where(sequence: sequence - 1).first
  end

  # @return [Flight, nil] The user's next flight, or `nil` if this is the latest
  #   flight or an as-yet unsequenced flight.

  def next
    return nil unless sequence
    @next ||= user.flights.where(sequence: sequence + 1).first
  end

  # @private
  def to_param() slug end
end

app/controllers/flights_controller.rb
# Controller for viewing a {User}'s {Flight Flights}.

class FlightsController < ApplicationController
  before_action :find_flight, except: :index
  before_action :owner_login_required, only: [ :edit, :update ]
  respond_to :html, :json

  # HTML
  # ====
  #
  # Displays a page that dynamically loads a list of flights and displays them
  # in a vaguely logbook-like format.
  #
  # |          |                                           |
  # |:---------|:------------------------------------------|
  # | `filter` | Passed to the JSON format of this action. |
  #
  # JSON
  # ====
  #
  # Returns information about flights in 50-long pages; used by the HTML view.
  # Flights are sorted by date descending.
  #
  # Parameters
  # ----------
  #
  # |               |                                                                                                       |
  # |:--------------|:------------------------------------------------------------------------------------------------------|
  # | `filter`      | If `all` (default), all flights are returned. If `blog`, only flights with blog entries are returned. |
  # | `last_record` | The ID of a record to load rows after (used for pagination).                                          |
  #
  # Routes
  # ======
  #
  # * `GET /flights`
  # * `GET /people/[person_id]/flights`
  # * `GET /airports/[airport_id]/flights`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                                                                                              |
  # |:-------------|:-------------------------------------------------------------------------------------------------------------|
  # | `person_id`  | The slug for a {Person}. Flights are limited to those in which that person was present.                      |
  # | `airport_id` | The {Airport#identifier identifier} for an {Airport}. Flights are limited to those arriving at that airport. |

  def index
    params['filter'] ||= 'all'

    respond_to do |format|
      format.html
      format.json do
        if params['person_id'] then
          person = Person.find_from_slug!(params['person_id'], request.subdomain)
          @flights = person.flights.includes(:slugs, occupants: { person: :slugs })
        elsif params['airport_id'] then
          airport = Airport.with_ident(params['airport_id']).first || raise(ActiveRecord::RecordNotFound)
          destination = subdomain_owner.destinations.find_by_airport_id(airport.id) || raise(ActiveRecord::RecordNotFound)
          @flights = subdomain_owner.flights.includes(:slugs, occupants: { person: :slugs }).where(destination_id: destination.id)
        else
          @flights = subdomain_owner.flights.includes(:slugs, occupants: { person: :slugs })
        end

        @flights = @flights.
          includes(:aircraft, :photographs, occupants: { person: :slugs }).
          order('sequence DESC').
          limit(50)
        @flights = @flights.where(has_blog: true) if params['filter'] == 'blog'

        if params['last_record'] and params['last_record'].to_i > 0 then
          @flights = @flights.where('sequence < ?', params['last_record'].to_i)
        end

        render(json: build_json(@flights).to_json)
      end
    end
  end

  # Displays information about a {Flight}, including its blog entry and
  # {Photograph photos}.
  #
  # Routes
  # ------
  #
  # * `GET /flights/[id]`
  #
  # Path Parameters
  # ---------------
  #
  # |      |                           |
  # |:-----|:--------------------------|
  # | `id` | The slug of the {Flight}. |

  def show
    respond_with @flight
  end

  # Displays a page where a user can write or edit a flight's blog entry, and
  # upload {Photograph photos}.
  #
  # Routes
  # ------
  #
  # * `GET /flights/[id]/edit`
  #
  # Path Parameters
  # ---------------
  #
  # |      |                           |
  # |:-----|:--------------------------|
  # | `id` | The slug of the {Flight}. |

  def edit
    @flight.photographs.build
    respond_with @flight
  end

  # Displays a page where a user can write or edit a flight's blog entry, and
  # upload {Photograph photos}.
  #
  # Routes
  # ------
  #
  # * `PATCH /flights/[id]/edit`
  #
  # Path Parameters
  # ---------------
  #
  # |      |                           |
  # |:-----|:--------------------------|
  # | `id` | The slug of the {Flight}. |
  #
  # Parameterized Hashes
  # --------------------
  #
  # |                      |                                                                                                     |
  # |:---------------------|:----------------------------------------------------------------------------------------------------|
  # | `flight`             | The attributes to update the flight with.                                                           |
  # | `flight[photograph]` | Nested attributes for the associated photographs. (Creating and destroying photographs is allowed.) |

  def update
    @flight.update_attributes flight_params
    respond_with @flight
  end

  private

  def find_flight
    @flight = Flight.find_from_slug!(params[:id], request.subdomain)
  end

  def build_json(flights)
    flights.map do |flight|
      {
        id: flight.sequence,
        url: flight_url(flight),
        date: l(flight.date, format: :logbook),
        aircraft: {
          ident: flight.aircraft.ident,
          type: flight.aircraft.type
        },
        remarks: flight.remarks,
        duration: flight.duration,
        photos: flight.photographs.sample(4).map do |photo|
          {
            thumbnail: view_context.image_path(photo.image.url(:logbook)),
            full: view_context.image_path(photo.image.url),
            caption: photo.caption
          }
        end,
        occupants: flight.occupants.map do |occupant|
          {
            photo: view_context.image_path(occupant.person.photo.url(:logbook)),
            url: person_url(occupant.person),
            name: occupant.person.name
          }
        end
      }
    end
  end

  def flight_params
    params.require(:flight).permit(:blog, photographs_attributes: [:image, :caption, :_destroy, :id])
  end
end

app/helpers/flights_helper.rb
# Helper module for views of {FlightsController}.

module FlightsHelper

  # @return [true, false] Whether to use the two-column blog layout.

  def show_blog?
    @flight.blog.present? or subdomain_owner?
  end

  # @return [Integer] A dimensionless value indicating the precedence of a crew
  #   role; higher values have higher rank.

  def precedence(role)
    return 8 if role == "Commander"
    return 7 if role == "Pilot in command"
    return 6 if role == "Flight instructor"
    return 5 if role == "Second in command"
    return 4 if role == "Relief pilot"
    return 3 if role == "Safety pilot"
    return 2 if role == "Engineer"
    return 1 if role == "Student pilot"
    # other roles
    return -1 if role == "Observer"
    return -2 if role == "Flight attendant"

    return -100 if role.nil?

    return 0
  end
end

app/views/flights/_photo.html.erb
<figure>
  <%= link_to image_tag(photo.image.url(:blog)), photo.image.url %>
  <% if photo.caption.present? %>
      <figcaption><%= photo.caption %></figcaption>
  <% end %>
</figure>

app/views/flights/edit.html.erb
<% content_for :title, "Edit Flight" %>
<%= render(partial: 'accounts/profile') %>

<%= form_with model: @flight, local: true do |f| %>
    <ul>
      <li>
        <%= f.text_area :blog, rows: 40, cols: 80, placeholder: "Write a blog entry" %>
        <p class="note">Format your blog entry using <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/syntax" %>.</p>
      </li>

      <li><h2>Add photos from your adventure</h2></li>
      <div id="easyuploader"></div>

      <%= f.fields_for :photographs do |fp| %>
          <li <%= 'id="new_photo"'.html_safe if fp.object.new_record? %>>
            <% if fp.object.new_record? %>
                <%= fp.file_field :image %><br />
            <% else %>
                <%= image_tag fp.object.image.url(:logbook) %>
            <% end %>
            <%= fp.text_field :caption, size: 80, maxlength: 300, placeholder: 'Caption your photo' %>
            <% if fp.object.persisted? %>
                <br /><%= fp.check_box :_destroy %> <%= fp.label :_destroy, "Delete this photograph" %>
            <% end %>
          </li>
      <% end %>

      <li class="submit"><%= f.submit %></li>
    </ul>
<% end %>

<%= content_for :javascripts do %>
    <script type="text/javascript">
        $(window).ready(function() {
            var currentRow;
            var uploader = $('#easyuploader').easyUploader("<%= raw j(flight_photographs_url(@flight, format: 'json')) %>", "photograph[image]", {
                maxSimultaneousUploads: 1,
                data: {"<%= raw j(request_forgery_protection_token.to_s) %>": "<%= raw j(form_authenticity_token.to_s) %>"}
            });
        });
    </script>
<% end %>

app/views/flights/index.html.erb
<% content_for :title, "Logbook" %>
<%= render(partial: 'accounts/profile') %>

<p id="filters">
  <%= link_to_unless params[:filter] == 'all', "All flights", url_for(filter: 'all') %> |
  <%= link_to_unless params[:filter] == 'blog', "Flights with blog entries", url_for(filter: 'blog') %>
</p>

<ol id="logbook"></ol>

<%= content_for :javascripts do %>
    <script type="text/javascript">
        $(window).ready(function() {
            $('#logbook').logbook("<%= raw j(flights_url(filter: params[:filter], format: :json)) %>");
        });
    </script>
<% end %>

app/views/flights/show.html.erb
<% content_for :title, "Flight to #{@flight.destination.airport.identifier} on #{l @flight.date, format: :flight}" %>
<%= render(partial: 'accounts/profile') %>

<section id="overview">
  <h1>
    <time datetime="<%= @flight.date.xmlschema %>"><%= l @flight.date, format: :flight %></time>
    <%= number_with_precision @flight.duration, precision: 1 %> hours
  </h1>
  <p><%= @flight.remarks %></p>
</section>

<section id="details">
  <% if show_blog? %>
      <div id="blog">
        <% if @flight.blog.present? %>
            <%= raw markdown.render(@flight.blog) %>
            <% if subdomain_owner? %>
                <p><%= link_to "Edit blog entry or add photos", edit_flight_url(@flight), class: 'button' %></p>
            <% end %>
        <% else %>
            <p>There is no blog entry for this flight. <%= link_to "Write one &rarr;".html_safe, edit_flight_url(@flight), class: 'button' %></p>
        <% end %>
      </div>
  <% end %>

  <div id="stats">
    <h2>Aircraft</h2>
    <div class="stat">
      <%= image_tag @flight.aircraft.image.url(:stat) %>
      <div>
        <h3><%= link_to @flight.aircraft.ident, "http://www.airport-data.com/aircraft/#{CGI.escape @flight.aircraft.ident}.html" %></h3>
        <p><%= @flight.aircraft.year %> <%= @flight.aircraft.long_type || @flight.aircraft.type %></p>
      </div>
    </div>

    <% @flight.occupants.includes(person: :slugs).sort { |c1, c2| precedence(c2.role) <=> precedence(c1.role) }.group_by(&:role).each do |role, occupants| %>
        <h2><%= occupants.many? ? role.pluralize : role %></h2>
        <% occupants.each do |occupant| %>
            <div class="stat">
              <%= link_to image_tag(occupant.person.photo.url(:stat)), occupant.person %>
              <div>
                <h3><%= link_to occupant.person.name, occupant.person %></h3>
                <p><%= pluralize_with_delimiter occupant.person.flights.count, 'flight' %></p>
              </div>
            </div>
        <% end %>
    <% end %>

    <h2>Route and stops</h2>
    <% @flight.destinations { |d| d.includes(:airport).limit(20) }.uniq.each do |destination| %>
        <div class="stat">
          <%= link_to image_tag(destination.photo.url(:stat)), destination.airport %>
          <div>
            <h3><%= link_to destination.airport.name, destination.airport %></h3>
            <p><%= destination.airport.city %>, <%= destination.airport.state %></p>
          </div>
        </div>
    <% end %>
    <% if @flight.stops.count > 18 %>
        <p>&hellip; and more &hellip;</p>
    <% end %>

    <% if show_blog? and not @flight.photographs.empty? %>
        <hr />
        <ul id="photos"></ul>
        <%= content_for :javascripts do %>
            <script type="text/javascript">
              $('#photos').carousel("<%= flight_photographs_url(@flight, format: 'json') %>", 'vertical')
            </script>
        <% end %>
    <% end %>
  </div>
</section>

<% if not show_blog? and not @flight.photographs.empty? %>
    <hr />
    <ul id="photos"></ul>
    <%= content_for :javascripts do %>
        <script type="text/javascript">
          $('#photos').carousel("<%= flight_photographs_url(@flight, format: 'json') %>", 'horizontal')
        </script>
    <% end %>
<% end %>

<nav>
  <% if @flight.previous %>
      <%= link_to "&larr; Previous flight".html_safe, @flight.previous, class: 'button-small' %>
  <% else %>
      <span class="button-small-disabled">&larr; Previous flight</span>
  <% end %>
  <% if @flight.next %>
      <%= link_to "Next flight &rarr;".html_safe, @flight.next, class: 'button-small' %>
  <% else %>
      <span class="button-small-disabled">Next flight &rarr;</span>
  <% end %>
</nav>