config/routes.rb
require 'subdomain_router'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints(subdomain: '') do
    get '' => redirect { |_, request| "http://www.#{request.host_with_port}" }
    get '*glob' => redirect { |_, request| "http://www.#{request.host_with_port}#{request.fullpath}" }
  end

  constraints(subdomain: SubdomainRouter::Config.default_subdomain) do
    resources :users, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    resources :photographs, only: :index

    root(to: 'users#new')

    # require 'sidekiq/web'
    # require 'admin_constraint'
    # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  end

  constraints(SubdomainRouter::Constraint) do
    resource :account, only: [:show, :edit, :update, :destroy]
    resources :airports, only: [:index, :show] do
      resources :flights, only: :index
    end
    resources :flights, only: [:index, :show, :edit, :update] do
      resources :photographs, only: [:index, :create]
    end
    resources :imports, only: [:new, :create, :show]
    resources :people, only: [:index, :show] do
      resources :flights, only: :index
    end

    get '' => 'accounts#show'
  end
end

app/models/airport.rb
# An airport that {Flight flights} can originate or terminate at. Airports are
# not linked to a {User} account, and cannot be edited by users (see
# {Destination}). Their information is imported from a NFDC FADDS distribution
# (see {AirportImporter}).
#
# Fields
# ------
#
# |               |                                                                                     |
# |:--------------|:------------------------------------------------------------------------------------|
# | `site_number` | The identifier used by the FAA for this airport's record in the FADDS database.     |
# | `lid`         | The FAA location identifier, a three- or four-letter code identifying this airport. |
# | `icao`        | The ICAO's four-letter identifier for this airport.                                 |
# | `iata`        | The IATA's three- or four-letter identifier for this airport.                       |
#
# Metadata
# --------
#
# |         |                                                              |
# |:--------|:-------------------------------------------------------------|
# | `name`  | The airport's full name.                                     |
# | `city`  | The name of the city that the airport serves.                |
# | `state` | The two-letter USPS code for the state containing the city.  |
# | `lat`   | The airport's latitude, in decimal degrees (north positive). |
# | `lon`   | The airport's longitude, in decimal degrees (east positive). |
#
# Associations
# ------------
#
# |                |                                                          |
# |:---------------|:---------------------------------------------------------|
# | `destinations` | The {Destination Destinations} referencing this airport. |

class Airport < ApplicationRecord
  include HasMetadataColumn

  STATES = %w( AL AK AS AZ AR CA CO CT DE DC FM FL GA GU HI ID IL IN IA KS KY LA
               ME MH MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND MP OH OK OR PW
               PA PR RI SC SD TN TX UT VT VI VA WA WV WI WY )

  has_many :destinations, dependent: :restrict_with_exception, inverse_of: :airport

  has_metadata_column(
      name:  {
          presence: true,
          length:   { maximum: 100 } },
      city:  {
          length:      { maximum: 100 },
          allow_blank: true },
      state: {
          inclusion:   { in: STATES },
          allow_blank: true },
      lat:   {
          type:         Float,
          numericality: { :>= => -90, :<= => 90 },
          allow_nil:    true },
      lon:   {
          numericality: { :>= => -180, :<= => 180 },
          allow_nil:    true
      }
  )

  validates :site_number,
            presence:   true,
            uniqueness: true,
            length:     { maximum: 11 }
  validates :lid,
            length:      { within: 3..4 },
            format:      { with: /\A[A-Z0-9]+\z/ },
            presence:    { if: ->(airport) { airport.icao.blank? and airport.iata.blank? } },
            allow_blank: true
  validates :icao,
            length:      { is: 4 },
            format:      { with: /\A[A-Z0-9]+\z/ },
            presence:    { if: ->(airport) { airport.lid.blank? and airport.iata.blank? } },
            allow_blank: true
  validates :iata,
            length:      { within: 3..4 },
            format:      { with: /\A[A-Z0-9]+\z/ },
            uniqueness:  { scope: [:lid, :icao] },
            presence:    { if: ->(airport) { airport.icao.blank? and airport.lid.blank? } },
            allow_blank: true

  attr_readonly :site_number

  scope :with_ident, ->(lid, iata=nil, icao=nil) {
    iata    ||= lid
    icao    ||= iata
    clauses = []
    clauses << 'lid = ?' if lid.present?
    clauses << 'iata = ?' if iata.present?
    clauses << 'icao = ?' if icao.present?
    where(clauses.join(' OR '), *[lid, iata, icao].select(&:present?))
  }

  # @return [String] The airport's LID, ICAO code, or IATA code.

  def identifier
    lid || icao || iata
  end

  # @private
  def to_param() identifier end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  respond_to :html
  before_action :find_airport, only: :show

  # HTML
  # ====
  #
  # Displays a page that dynamically loads a list of {Destination Destinations}.
  #
  # JSON
  # ====
  #
  # Returns information about destinations in 50-long pages; used by the HTML
  # view. Airports are returned in arbitrary order.
  #
  # Parameters
  # ----------
  #
  # |               |                                                              |
  # |:--------------|:-------------------------------------------------------------|
  # | `last_record` | The ID of a record to load rows after (used for pagination). |
  #
  # Routes
  # ======
  #
  # * `GET /airports`

  def index
    respond_to do |format|
      format.html do
        airport = subdomain_owner.destinations.first.try(:airport)
        if airport then
          @lat, @lon = airport.lat, airport.lon
        else
          @lat, @lon = 38.0, -122.0
        end
        # index.html.erb
      end

      format.json do
        destinations = subdomain_owner.destinations.
          includes(:airport).order('airport_id ASC').limit(50)

        if params['last_record'] then
          destinations = destinations.where('airport_id > ?', params['last_record'])
        end

        render(json: build_json(destinations).to_json)
      end
    end
  end

  # Displays information about a {Destination}.
  #
  # Routes
  # ------
  #
  # * `GET /airports/[id]`
  #
  # Path Parameters
  # ---------------
  #
  # |      |                                                       |
  # |:-----|:------------------------------------------------------|
  # | `id` | The {Airport#identifier identifier} of the {Airport}. |

  def show
    respond_with @destination
  end

  private

  def build_json(destinations)
    destinations.map do |dest|
      {
        airport_id: dest.airport_id,
        photo: view_context.image_path(dest.photo.url(:stat)),
        url: airport_url(dest.airport),
        airport: {
          name: dest.airport.name,
          city: dest.airport.city,
          state: dest.airport.state,
          identifier: dest.airport.identifier,
          lat: dest.airport.lat,
          lon: dest.airport.lon
        }
      }
    end
  end

  def find_airport
    @airport = Airport.with_ident(params[:id]).first || raise(ActiveRecord::RecordNotFound)
    @destination = subdomain_owner.destinations.find_by_airport_id(@airport.id) || raise(ActiveRecord::RecordNotFound)
  end
end

app/views/airports/index.html.erb
<% content_for :title, "Airports" %>
<%= render(partial: 'accounts/profile') %>

<p id="loading"><%= image_tag 'spinner.gif' %> Loading airports&hellip;</p>

<section id="airports_view">
  <div id="map"></div>
  <ul id="list"></ul>
</section>

<%= content_for :javascripts do %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
        $(window).ready(function() {
            var myOptions = {
                zoom: 4,
                center: new google.maps.LatLng(<%= @lat %>, <%= @lon %>),
                mapTypeId: google.maps.MapTypeId.TERRAIN
            };
            var map = new google.maps.Map(document.getElementById("map"),
                                          myOptions);
            var bounds = new google.maps.LatLngBounds();

            var loader = function(data) {
                if (data.length == 0) {
                    map.fitBounds(bounds);
                    $('#loading').fadeOut();
                    return;
                }

                $.each(data, function(_, dest) {
                    var pos = new google.maps.LatLng(dest.airport.lat, dest.airport.lon);
                    bounds.extend(pos);

                    var marker = new google.maps.Marker({
                                               map: map,
                                               position: pos,
                                               title: dest.airport.name
                                           });

                    google.maps.event.addListener(marker, 'click', function() {
                        $('#list>li').removeClass('highlighted');
                        $('li#airport_' + dest.airport_id).addClass('highlighted');
                        $('#list').scrollTo($('li#airport_' + dest.airport_id), 500);
                    });

                    var li = $('<li/>').attr('id', 'airport_' + dest.airport_id).appendTo($('#list'));
                    $('<img/>').attr('src', dest.photo).appendTo(li);
                    var details = $('<div/>').addClass('details').appendTo(li);
                    $('<h1/>').append($('<a/>').text(dest.airport.name).attr('href', dest.url)).appendTo(details);
                    $('<p/>').text(dest.airport.city + ', ' + dest.airport.state).appendTo(details);
                });

                $.getJSON("<%= raw j(airports_url(format: 'json')) %>",
                          { last_record: data[data.length - 1].airport_id },
                          loader);
            };

            $.getJSON("<%= raw j(airports_url(format: 'json')) %>", loader);
        });
    </script>
<% end %>

app/views/airports/show.html.erb
<% content_for :title, @destination.airport.name %>

<section id="title">
  <%= image_tag @destination.photo.url(:profile), alt: @destination.airport.name %>
  <div id="name">
    <h1><%= @destination.airport.name %> <span id="airport_ident">(<%= @destination.airport.identifier %>)</span></h1>
    <% if @notes %>
        <div id="notes"><%= raw markdown.render(@destination.notes) %></div>
    <% end %>
    <p id="vitals">
      <%= @destination.airport.city %>, <%= @destination.airport.state %> &bull;
      <%= pluralize_with_delimiter @destination.flights_count, 'flight' %> (to, from, or enroute)
    </p>
    <p><%= link_to "More Information", "http://www.airnav.com/airport/#{CGI.escape @destination.airport.identifier}", class: 'button' %></p>
  </div>
</section>
<p><%= link_to "&larr; All airports".html_safe, airports_url, class: 'button' %></p>

<h1>Flights to <%= @destination.airport.identifier %></h1>
<ol id="logbook"></ol>

<%= content_for :javascripts do %>
    <script type="text/javascript">
        $(window).ready(function() {
            $('#logbook').logbook("<%= raw j(airport_flights_url(@destination.airport, format: :json)) %>");
        });
    </script>
<% end %>