config/routes.rb
require 'subdomain_router'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints(subdomain: '') do
    get '' => redirect { |_, request| "http://www.#{request.host_with_port}" }
    get '*glob' => redirect { |_, request| "http://www.#{request.host_with_port}#{request.fullpath}" }
  end

  constraints(subdomain: SubdomainRouter::Config.default_subdomain) do
    resources :users, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    resources :photographs, only: :index

    root(to: 'users#new')

    # require 'sidekiq/web'
    # require 'admin_constraint'
    # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  end

  constraints(SubdomainRouter::Constraint) do
    resource :account, only: [:show, :edit, :update, :destroy]
    resources :airports, only: [:index, :show] do
      resources :flights, only: :index
    end
    resources :flights, only: [:index, :show, :edit, :update] do
      resources :photographs, only: [:index, :create]
    end
    resources :imports, only: [:new, :create, :show]
    resources :people, only: [:index, :show] do
      resources :flights, only: :index
    end

    get '' => 'accounts#show'
  end
end

app/controllers/application_controller.rb
require 'subdomain_router'
require 'authentication_helpers'

# @abstract
#
# Superclass for all controllers in this application.

class ApplicationController < ActionController::Base
  include SubdomainRouter::Controller
  include AuthenticationHelpers
  before_bugsnag_notify :add_user_info_to_bugsnag

  # The User-Agent names of supported web browsers.
  SUPPORTED_BROWSERS = [ :Chrome, :chrome, :Safari, :safari ]

  before_action :warn_for_incompatible_browsers

  layout 'application'

  rescue_from(ActiveRecord::RecordNotFound) { render(file: Rails.root.join('public', '404.html'), status: :not_found) }
  rescue_from(ActiveRecord::RecordInvalid) { render(file: Rails.root.join('public', '422.html'), status: :unprocessable_entity) }

  protected

  # @return [User, nil] The user that owns the current subdomain, or `nil` for
  #   the default subdomain (e.g., "www").

  def subdomain_owner
    user_id = request.env['subdomain_router.subdomain_owner']
    user_id ? User.find(user_id) : User.active.for_subdomain(request.subdomain).first
  end
  helper_method :subdomain_owner

  private

  def warn_for_incompatible_browsers
    return unless request.env['HTTP_USER_AGENT'].present?
    agent = Agent.new(request.env['HTTP_USER_AGENT'])
    @unsupported = !SUPPORTED_BROWSERS.include?(agent.name)
    return true
  end

  def add_user_info_to_bugsnag(report)
    report.user = {
        id:    current_user.id,
        email: current_user.email
    } if logged_in?
  end
end

app/helpers/application_helper.rb
# Helper module for all views.

module ApplicationHelper

  # A combination of `pluralize` and `number_with_delimiter`.
  #
  # @param [Integer] count The number of items. This number will be formatted.
  # @param [String] singular The string to append to the count if the count is
  #   one.
  # @param [String] plural The string to append to the count if the count is not
  #   one.

  def pluralize_with_delimiter(count, singular, plural=nil)
    t 'helpers.application.pluralize_with_delimiter.format',
      count: number_with_delimiter(count || 0),
      thing: (count == 1 ? singular : (plural || singular.pluralize))
  end

  # @return [Redcarpet::Markdown] The Markdown renderer for pilot-generated
  #   markdown code.

  def markdown
    $markdown ||= Redcarpet::Markdown.new(SmartyPantsHTML.new(no_images: true, safe_links_only: true, filter_html: true), autolink: true)
  end
end

app/views/application/_assets.html.erb
<!-- CSS: implied media="all" -->
<%= stylesheet_link_tag 'application' %>

<!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
<!--[if IE ]><%= javascript_include_tag 'ie' %><![endif]-->

app/views/application/_footer.html.erb
<footer>
  <p>
    Copyright &copy;2011 <%= link_to "Tim Morgan", "http://www.timothymorgan.info" %>. All rights reserved. |
    <%= mail_to 'flightseein@timothymorgan.info', "Contact Me", encode: :javascript %>
    <% unless logged_in? %>
        | Pilot? Like what you see? <%= link_to "Get your own.", root_url(subdomain: false) %>
    <% end %>
  </p>
</footer>

app/views/application/_ga.html.erb
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-601005-5']);
    _gaq.push(['_setDomainName', '.flightsee.in']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
</script>

app/views/application/_header.html.erb
<header>
  <%= link_to image_tag('title.jpg', alt: "flightseein&rsquo;".html_safe), root_url %>
  <p id="login">
    <% if logged_in? %>
        <%= link_to "Log out", session_url(subdomain: 'www'), method: :delete, class: 'button-small' %>
    <% else %>
        <%= link_to "Log in", new_session_url(subdomain: false), class: 'button-small' %>
    <% end %>
  </p>
  <ul id="flashes" style="display: none">
    <% if @unsupported %>
        <li id="unsupported">Warning! Your Web browser isn&rsquo;t fully
          supported. Some web pages may look strange. For the best experience,
          download either
          <%= link_to "Google Chrome", "http://www.google.com/chrome/" %> or
          <%= link_to "Safari", "http://www.apple.com/safari/" %>.
        </li>
    <% end %>
    <% if flash[:alert] %>
        <li id="flash-alert"><%= flash[:alert] %></li>
    <% end %>
    <% if flash[:notice] %>
        <li id="flash-notice"><%= flash[:notice] %></li>
    <% end %>
  </ul>
</header>

app/views/application/_javascripts.html.erb
<!-- JavaScript at the bottom for fast page loading -->
<%= javascript_include_tag 'application' %>
<!-- end scripts-->

<!--[if lt IE 7 ]>
<script type="javascript">DD_belatedPNG.fix("img, .png"); // Fix any <img> or .png images. Also, please read goo.gl/mZiyb </script><![endif]-->

<% if Rails.env.production? %>
    <script type="text/javascript">
        var _gaq = [
            ["_setAccount","UA-XXXXX-X"],
            ["_trackPageview"]
        ];
        (function(d, t) {
            var g = d.createElement(t),s = d.getElementsByTagName(t)[0];
            g.async = 1;
            g.src = ("https:" == location.protocol ? "//ssl" : "//www") + ".google-analytics.com/ga.js";
            s.parentNode.insertBefore(g, s)
        }(document, "script"));
    </script>
<% end %>

<%= yield :javascripts %>

app/views/application/_metas.html.erb
<meta charset="utf-8">

<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
Remove this if you use the .htaccess -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>
  <% if content_for? :title %>
      <%= yield :title %> |
  <% end %>
  <% if subdomain_owner %>
      <%= subdomain_owner.best_name %>&rsquo;s
  <% end %>
  flightseein&rsquo;
</title>
<meta name="description" content="A visual, interactive way to show off your logbook.">
<meta name="author" content="Tim Morgan">

<!-- Mobile viewport optimized: j.mp/bplateviewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<%= csrf_meta_tags %>