config/routes.rb
require 'subdomain_router'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints(subdomain: '') do
    get '' => redirect { |_, request| "http://www.#{request.host_with_port}" }
    get '*glob' => redirect { |_, request| "http://www.#{request.host_with_port}#{request.fullpath}" }
  end

  constraints(subdomain: SubdomainRouter::Config.default_subdomain) do
    resources :users, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    resources :photographs, only: :index

    root(to: 'users#new')

    # require 'sidekiq/web'
    # require 'admin_constraint'
    # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  end

  constraints(SubdomainRouter::Constraint) do
    resource :account, only: [:show, :edit, :update, :destroy]
    resources :airports, only: [:index, :show] do
      resources :flights, only: :index
    end
    resources :flights, only: [:index, :show, :edit, :update] do
      resources :photographs, only: [:index, :create]
    end
    resources :imports, only: [:new, :create, :show]
    resources :people, only: [:index, :show] do
      resources :flights, only: :index
    end

    get '' => 'accounts#show'
  end
end

app/controllers/accounts_controller.rb
# Controller for modifying and deleting a {User}'s account.

class AccountsController < ApplicationController
  before_action :owner_login_required, only: [ :edit, :update, :destroy ]
  respond_to :html

  # Displays information about a {User}. This serves as the user's home page.
  #
  # Routes
  # ------
  #
  # * `GET /`

  def show
    @flight_count = subdomain_owner.flights.count
    @pax_count = subdomain_owner.people.participating.not_me.count
    @airport_count = subdomain_owner.destinations.count

    @flight_images = subdomain_owner.flights.includes(:slugs).order('sequence DESC').limit(4)

    @pax_images = subdomain_owner.people.with_photo.participating.not_me.includes(:slugs).limit(50).sample(4)
    @pax_images += subdomain_owner.people.without_photo.participating.not_me.includes(:slugs).limit(50).sample(4 - @pax_images.size) unless @pax_images.size == 4
    @pax_images.shuffle!

    @airport_images = subdomain_owner.destinations.with_photo.includes(:airport).limit(50).sample(4)
    @airport_images += subdomain_owner.destinations.without_photo.includes(:airport).limit(50).sample(4 - @airport_images.size) unless @airport_images.size == 4
    @airport_images.shuffle!

    respond_with subdomain_owner
  end

  # Displays a page where a {User} can edit his information.
  #
  # Routes
  # ------
  #
  # * `GET /account/edit`

  def edit
    respond_with current_user
  end

  # Updates the current {User}.
  #
  # Routes
  # ------
  #
  # * `PATCH /account`
  #
  # Parameterized Hashes
  # --------------------
  #
  # |        |                                       |
  # |:-------|:--------------------------------------|
  # | `user` | The information for the user account. |

  def update
    current_user.update_attributes(user_params)
    respond_with current_user do |format|
      format.html do
        if current_user.valid? then
          redirect_to root_url(subdomain: current_user.subdomain)
        else
          render 'edit'
        end
      end
    end
  end

  # Deletes a {User} account and logs the user out.
  #
  # Routes
  # ------
  #
  # * `DELETE /account`

  def destroy
    current_user.update_attribute :active, false
    log_out

    respond_to do |format|
      format.html { redirect_to root_url, notice: t('controllers.accounts.destroy.done') }
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :name, :quote, :subdomain, :avatar)
  end
end

app/views/accounts/_profile.html.erb
<section id="title">
  <%= link_to image_tag(subdomain_owner.avatar.url(:profile_small), alt: subdomain_owner.best_name), root_url %>
  <div id="name">
    <h1><%= link_to subdomain_owner.best_name, root_url %></h1>
    <p id="vitals">
      <%= link_to pluralize_with_delimiter(subdomain_owner.people.participating.not_me.count, 'passenger'), people_url %> &bull;
      <%= link_to pluralize_with_delimiter(subdomain_owner.flights.count, 'flight'), flights_url %>
    </p>
  </div>
</section>

app/views/accounts/edit.html.erb
<p id="call-to-action">Edit your profile:</p>
<%= form_with model: current_user, url: account_url, local: true do |f| %>
    <ul>
      <li><%= f.text_field :name, placeholder: t('activerecord.attributes.user.name') %></li>
      <li>
        <%= f.text_area :quote, placeholder: t('activerecord.attributes.user.quote'), rows: 3, cols: 22 %>
        <p class="note">Format your quote using <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/syntax" %>.</p>
      </li>
      <li><%= f.label :avatar %>: <%= f.file_field :avatar %></li>

      <li class="submit"><%= f.submit %></li>
    </ul>
<% end %>

<p>
  <%= link_to "&larr; Return to your home page".html_safe, root_url, class: 'button-small' %>
  <%= link_to "Delete my account", account_url, method: :delete, data: { confirm: "This will prevent anyone from viewing your account. Are you sure?" }, class: 'button-small' %>
</p>

app/views/accounts/show.html.erb
<section id="title">
  <%= image_tag subdomain_owner.avatar.url(:profile), alt: subdomain_owner.best_name %>
  <div id="name">
    <h1><%= subdomain_owner.best_name %></h1>
    <% if subdomain_owner.quote.present? %>
        <div id="quote"><%= raw markdown.render(subdomain_owner.quote) %></div>
    <% end %>
    <p id="vitals">
      <% if subdomain_owner.certificate %>
          <%= t "models.user.certificate.#{subdomain_owner.certificate}" %>
          <%= "(instrument)" if subdomain_owner.has_instrument? %>
          <% if subdomain_owner.certification_date %>
            since <%= l subdomain_owner.certification_date, format: :vitals %>
          <% end %>
          &bull;
      <% end %>
      <%= number_with_precision subdomain_owner.hours, precision: 1 %> hours
    </p>
    <% if subdomain_owner? %>
        <p><%= link_to "Edit your profile", edit_account_url, class: 'button' %></p>
    <% end %>
  </div>
</section>

<% if subdomain_owner? %>
    <p id="import-link">
      <% if @flight_count.zero? %>
          &rarr; Import your digital logbook to finish your profile!
      <% else %>
          &rarr; Update your profile by re-importing your logbook.
      <% end %>
      <%= link_to "Import your logbook", new_import_url, class: 'button' %>
    </p>
<% end %>

<section id="stats">
  <ul id="row-flights" class="progrid">
    <li class="statbox nofade center" fakehref="<%= flights_url %>">
      <h1><%= number_with_delimiter @flight_count %></h1>
      <p><%= "adventure".send(@flight_count == 1 ? :self : :pluralize) %></p>
    </li>
    <% @flight_images.each do |flight| %>
        <% if flight.photographs.empty? %>
            <li class="no-image center" fakehref="<%= flight_url flight %>">
              <h1><%= raw flight.destinations.map(&:airport).map(&:identifier).join(" &rarr; ") %></h1>
              <p><%= l flight.date, format: :carousel %></p>
            </li>
        <% else %>
            <li><%= link_to image_tag(flight.photographs.limit(4).sample.image.url(:carousel), alt: "#{flight.origin.airport.identifier} to #{flight.destination.airport.identifier}"), flight %></li>
        <% end %>
    <% end %>
  </ul>

  <ul id="row-pax" class="progrid">
    <li class="statbox nofade center" fakehref="<%= people_url %>">
      <h1><%= number_with_delimiter @pax_count %></h1>
      <p><%= "passenger".send(@pax_count == 1 ? :self : :pluralize) %></p>
    </li>
    <% @pax_images.each do |pax| %>
        <% if pax.has_photo? %>
            <li><%= link_to image_tag(pax.photo.url(:carousel), alt: pax.name), pax %></li>
        <% else %>
            <li class="no-image center" fakehref="<%= person_url pax %>">
              <h1><%= pax.name %></h1>
              <p><%= number_with_precision pax.hours, precision: 1 %> hours</p>
            </li>
        <% end %>
    <% end %>
  </ul>

  <ul id="row-airports" class="progrid">
    <li class="statbox nofade center" fakehref="<%= airports_url %>">
      <h1><%= number_with_delimiter @airport_count %></h1>
      <p><%= "destination".send(@airport_count == 1 ? :self : :pluralize) %></p>
    </li>
    <% @airport_images.each do |dest| %>
        <% if dest.has_photo? %>
            <li><%= link_to image_tag(dest.photo.url(:carousel), alt: dest.airport.name), dest.airport %></li>
        <% else %>
            <li class="no-image center" fakehref="<%= airport_url dest.airport %>">
              <h1><%= dest.airport.identifier %></h1>
              <p><%= dest.airport.name %></p>
            </li>
        <% end %>
    <% end %>
  </ul>
</section>